[package]
name = "rust-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
miette = { version="7.4.0",features=["fancy"]}
thiserror = "2.0.7"
clap = { version="4.5.23",features=["derive"]}
